### ISSUE TITLE
Python tests failures on macOS

### ISSUE THREAD

**Issue by lgeretti** [ariadne-cps/ariadne#445]
Recently all the python tests (except for the basic import) fail in a rather irregular way with a SegFault on macOS.

**Comment by lgeretti** [comment]
The commit responsible for the failure is 85e74d78ed37ccb43f9ebf73049f2fbcf8ff174c

**Comment by lgeretti** [comment]
By upgrading to the 2.6.1 version of pybind11, now the segfaults become normal errors. However, both macOS and Ubuntu fail. On macOS using AppleClang we have the following problems.

In test_calculus.py, the first issue that we get is

bx=BoxDomainType([{Dyadic(1):3},{-1:2},{-3:3}])
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: unhashable type: 'ariadne.Dyadic'

Likewise, at the bottom of test_linear_algebra.py, we get
Ab=ValidatedMatrix([[{exact(1.875):exact(2.125)},{exact(0.875):exact(1.125)}],[{exact(0.875):exact(1.125)},{exact(0.875):exact(1.125)}]],pr)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: unhashable type: 'ariadne.Dyadic'

Finally, the first issue in test_geometry.py is
xivl=FloatDPExactInterval({-x:x})
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: unhashable type: 'ariadne.FloatDPValue'

**Comment by lgeretti** [comment]
This is seemingly addressed by using the latest Python 3.9.1 from Homebrew, under macOS 11.1.
