### ISSUE TITLE
Python Examples Fail to Run 

### ISSUE THREAD

**Issue by mpophal2018** [ariadne-cps/ariadne#675]
When running Ariadne in a Docker container I can't run the python example 'hybrid_evolution_example.py', below is the console output when I try. 

Traceback (most recent call last):
  File "hybrid_evolution_tutorial.py", line 299, in <module>
    system = get_system()
  File "hybrid_evolution_tutorial.py", line 248, in get_system
    system = CompositeHybridAutomaton("watertank",[get_tank(),get_valve(),get_controller()])
  File "hybrid_evolution_tutorial.py", line 28, in get_tank
    alpha = RealConstant("alpha",dec_(0.02))
NameError: name 'dec_' is not defined

**Comment by akaph2p** [comment]
Hi @mpophal2018 ,

Were you able to resolve this issue?

**Comment by mpophal2018** [comment]
Hello @akaph2p, 

I don't think I was able to resolve this, and I ended up needing something else for my purposes. We used KeYmaera X instead so sorry I can't be of more help.
